// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var HdpMessage = exports.HdpMessage = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Request = exports.Request = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Response = exports.Response = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineHdpMessage()
defineRequest()
defineResponse()

function defineHdpMessage () {
  HdpMessage.encodingLength = encodingLength
  HdpMessage.encode = encode
  HdpMessage.decode = decode

  function encodingLength (obj) {
    var length = 0
    if ((+defined(obj.request) + +defined(obj.response)) > 1) throw new Error("only one of the properties defined in oneof msg can be set")
    if (!defined(obj.id)) throw new Error("id is required")
    var len = encodings.varint.encodingLength(obj.id)
    length += 1 + len
    if (defined(obj.request)) {
      var len = Request.encodingLength(obj.request)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    if (defined(obj.response)) {
      var len = Response.encodingLength(obj.response)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if ((+defined(obj.request) + +defined(obj.response)) > 1) throw new Error("only one of the properties defined in oneof msg can be set")
    if (!defined(obj.id)) throw new Error("id is required")
    buf[offset++] = 8
    encodings.varint.encode(obj.id, buf, offset)
    offset += encodings.varint.encode.bytes
    if (defined(obj.request)) {
      buf[offset++] = 18
      varint.encode(Request.encodingLength(obj.request), buf, offset)
      offset += varint.encode.bytes
      Request.encode(obj.request, buf, offset)
      offset += Request.encode.bytes
    }
    if (defined(obj.response)) {
      buf[offset++] = 26
      varint.encode(Response.encodingLength(obj.response), buf, offset)
      offset += varint.encode.bytes
      Response.encode(obj.response, buf, offset)
      offset += Response.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      id: 0,
      request: null,
      response: null
    }
    var found0 = false
    while (true) {
      if (end <= offset) {
        if (!found0) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.id = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        found0 = true
        break
        case 2:
        delete obj.response
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.request = Request.decode(buf, offset, offset + len)
        offset += Request.decode.bytes
        break
        case 3:
        delete obj.request
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.response = Response.decode(buf, offset, offset + len)
        offset += Response.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineRequest () {
  var Handshake = Request.Handshake = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Ls = Request.Ls = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Read = Request.Read = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  defineHandshake()
  defineLs()
  defineRead()

  function defineHandshake () {
    Handshake.encodingLength = encodingLength
    Handshake.encode = encode
    Handshake.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.token)) throw new Error("token is required")
      var len = encodings.bytes.encodingLength(obj.token)
      length += 1 + len
      if (defined(obj.version)) {
        var len = encodings.string.encodingLength(obj.version)
        length += 1 + len
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.token)) throw new Error("token is required")
      buf[offset++] = 10
      encodings.bytes.encode(obj.token, buf, offset)
      offset += encodings.bytes.encode.bytes
      if (defined(obj.version)) {
        buf[offset++] = 18
        encodings.string.encode(obj.version, buf, offset)
        offset += encodings.string.encode.bytes
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        token: null,
        version: ""
      }
      var found0 = false
      while (true) {
        if (end <= offset) {
          if (!found0) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.token = encodings.bytes.decode(buf, offset)
          offset += encodings.bytes.decode.bytes
          found0 = true
          break
          case 2:
          obj.version = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineLs () {
    Ls.encodingLength = encodingLength
    Ls.encode = encode
    Ls.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (defined(obj.path)) {
        var len = encodings.string.encodingLength(obj.path)
        length += 1 + len
      }
      if (defined(obj.searchterm)) {
        var len = encodings.string.encodingLength(obj.searchterm)
        length += 1 + len
      }
      if (defined(obj.recursive)) {
        var len = encodings.bool.encodingLength(obj.recursive)
        length += 1 + len
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (defined(obj.path)) {
        buf[offset++] = 10
        encodings.string.encode(obj.path, buf, offset)
        offset += encodings.string.encode.bytes
      }
      if (defined(obj.searchterm)) {
        buf[offset++] = 18
        encodings.string.encode(obj.searchterm, buf, offset)
        offset += encodings.string.encode.bytes
      }
      if (defined(obj.recursive)) {
        buf[offset++] = 24
        encodings.bool.encode(obj.recursive, buf, offset)
        offset += encodings.bool.encode.bytes
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        path: "",
        searchterm: "",
        recursive: false
      }
      while (true) {
        if (end <= offset) {
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.path = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          break
          case 2:
          obj.searchterm = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          break
          case 3:
          obj.recursive = encodings.bool.decode(buf, offset)
          offset += encodings.bool.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineRead () {
    Read.encodingLength = encodingLength
    Read.encode = encode
    Read.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.path)) throw new Error("path is required")
      var len = encodings.string.encodingLength(obj.path)
      length += 1 + len
      if (defined(obj.start)) {
        var len = encodings.varint.encodingLength(obj.start)
        length += 1 + len
      }
      if (defined(obj.end)) {
        var len = encodings.varint.encodingLength(obj.end)
        length += 1 + len
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.path)) throw new Error("path is required")
      buf[offset++] = 10
      encodings.string.encode(obj.path, buf, offset)
      offset += encodings.string.encode.bytes
      if (defined(obj.start)) {
        buf[offset++] = 16
        encodings.varint.encode(obj.start, buf, offset)
        offset += encodings.varint.encode.bytes
      }
      if (defined(obj.end)) {
        buf[offset++] = 24
        encodings.varint.encode(obj.end, buf, offset)
        offset += encodings.varint.encode.bytes
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        path: "",
        start: 0,
        end: 0
      }
      var found0 = false
      while (true) {
        if (end <= offset) {
          if (!found0) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.path = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          found0 = true
          break
          case 2:
          obj.start = encodings.varint.decode(buf, offset)
          offset += encodings.varint.decode.bytes
          break
          case 3:
          obj.end = encodings.varint.decode(buf, offset)
          offset += encodings.varint.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  Request.encodingLength = encodingLength
  Request.encode = encode
  Request.decode = decode

  function encodingLength (obj) {
    var length = 0
    if ((+defined(obj.handshake) + +defined(obj.ls) + +defined(obj.read)) > 1) throw new Error("only one of the properties defined in oneof msg can be set")
    if (defined(obj.handshake)) {
      var len = Handshake.encodingLength(obj.handshake)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    if (defined(obj.ls)) {
      var len = Ls.encodingLength(obj.ls)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    if (defined(obj.read)) {
      var len = Read.encodingLength(obj.read)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if ((+defined(obj.handshake) + +defined(obj.ls) + +defined(obj.read)) > 1) throw new Error("only one of the properties defined in oneof msg can be set")
    if (defined(obj.handshake)) {
      buf[offset++] = 10
      varint.encode(Handshake.encodingLength(obj.handshake), buf, offset)
      offset += varint.encode.bytes
      Handshake.encode(obj.handshake, buf, offset)
      offset += Handshake.encode.bytes
    }
    if (defined(obj.ls)) {
      buf[offset++] = 18
      varint.encode(Ls.encodingLength(obj.ls), buf, offset)
      offset += varint.encode.bytes
      Ls.encode(obj.ls, buf, offset)
      offset += Ls.encode.bytes
    }
    if (defined(obj.read)) {
      buf[offset++] = 26
      varint.encode(Read.encodingLength(obj.read), buf, offset)
      offset += varint.encode.bytes
      Read.encode(obj.read, buf, offset)
      offset += Read.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      handshake: null,
      ls: null,
      read: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        delete obj.ls
        delete obj.read
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.handshake = Handshake.decode(buf, offset, offset + len)
        offset += Handshake.decode.bytes
        break
        case 2:
        delete obj.handshake
        delete obj.read
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.ls = Ls.decode(buf, offset, offset + len)
        offset += Ls.decode.bytes
        break
        case 3:
        delete obj.handshake
        delete obj.ls
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.read = Read.decode(buf, offset, offset + len)
        offset += Read.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineResponse () {
  var Handshake = Response.Handshake = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Ls = Response.Ls = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Read = Response.Read = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var EndResponse = Response.EndResponse = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Success = Response.Success = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  defineHandshake()
  defineLs()
  defineRead()
  defineEndResponse()
  defineSuccess()

  function defineHandshake () {
    Handshake.encodingLength = encodingLength
    Handshake.encode = encode
    Handshake.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.token)) throw new Error("token is required")
      var len = encodings.bytes.encodingLength(obj.token)
      length += 1 + len
      if (defined(obj.version)) {
        var len = encodings.string.encodingLength(obj.version)
        length += 1 + len
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.token)) throw new Error("token is required")
      buf[offset++] = 10
      encodings.bytes.encode(obj.token, buf, offset)
      offset += encodings.bytes.encode.bytes
      if (defined(obj.version)) {
        buf[offset++] = 18
        encodings.string.encode(obj.version, buf, offset)
        offset += encodings.string.encode.bytes
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        token: null,
        version: ""
      }
      var found0 = false
      while (true) {
        if (end <= offset) {
          if (!found0) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.token = encodings.bytes.decode(buf, offset)
          offset += encodings.bytes.decode.bytes
          found0 = true
          break
          case 2:
          obj.version = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineLs () {
    var Entry = Ls.Entry = {
      buffer: true,
      encodingLength: null,
      encode: null,
      decode: null
    }

    defineEntry()

    function defineEntry () {
      Entry.encodingLength = encodingLength
      Entry.encode = encode
      Entry.decode = decode

      function encodingLength (obj) {
        var length = 0
        if (!defined(obj.name)) throw new Error("name is required")
        var len = encodings.string.encodingLength(obj.name)
        length += 1 + len
        if (!defined(obj.size)) throw new Error("size is required")
        var len = encodings.varint.encodingLength(obj.size)
        length += 1 + len
        if (!defined(obj.isDir)) throw new Error("isDir is required")
        var len = encodings.bool.encodingLength(obj.isDir)
        length += 1 + len
        return length
      }

      function encode (obj, buf, offset) {
        if (!offset) offset = 0
        if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
        var oldOffset = offset
        if (!defined(obj.name)) throw new Error("name is required")
        buf[offset++] = 10
        encodings.string.encode(obj.name, buf, offset)
        offset += encodings.string.encode.bytes
        if (!defined(obj.size)) throw new Error("size is required")
        buf[offset++] = 16
        encodings.varint.encode(obj.size, buf, offset)
        offset += encodings.varint.encode.bytes
        if (!defined(obj.isDir)) throw new Error("isDir is required")
        buf[offset++] = 24
        encodings.bool.encode(obj.isDir, buf, offset)
        offset += encodings.bool.encode.bytes
        encode.bytes = offset - oldOffset
        return buf
      }

      function decode (buf, offset, end) {
        if (!offset) offset = 0
        if (!end) end = buf.length
        if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
        var oldOffset = offset
        var obj = {
          name: "",
          size: 0,
          isDir: false
        }
        var found0 = false
        var found1 = false
        var found2 = false
        while (true) {
          if (end <= offset) {
            if (!found0 || !found1 || !found2) throw new Error("Decoded message is not valid")
            decode.bytes = offset - oldOffset
            return obj
          }
          var prefix = varint.decode(buf, offset)
          offset += varint.decode.bytes
          var tag = prefix >> 3
          switch (tag) {
            case 1:
            obj.name = encodings.string.decode(buf, offset)
            offset += encodings.string.decode.bytes
            found0 = true
            break
            case 2:
            obj.size = encodings.varint.decode(buf, offset)
            offset += encodings.varint.decode.bytes
            found1 = true
            break
            case 3:
            obj.isDir = encodings.bool.decode(buf, offset)
            offset += encodings.bool.decode.bytes
            found2 = true
            break
            default:
            offset = skip(prefix & 7, buf, offset)
          }
        }
      }
    }

    Ls.encodingLength = encodingLength
    Ls.encode = encode
    Ls.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (defined(obj.entries)) {
        for (var i = 0; i < obj.entries.length; i++) {
          if (!defined(obj.entries[i])) continue
          var len = Entry.encodingLength(obj.entries[i])
          length += varint.encodingLength(len)
          length += 1 + len
        }
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (defined(obj.entries)) {
        for (var i = 0; i < obj.entries.length; i++) {
          if (!defined(obj.entries[i])) continue
          buf[offset++] = 10
          varint.encode(Entry.encodingLength(obj.entries[i]), buf, offset)
          offset += varint.encode.bytes
          Entry.encode(obj.entries[i], buf, offset)
          offset += Entry.encode.bytes
        }
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        entries: []
      }
      while (true) {
        if (end <= offset) {
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.entries.push(Entry.decode(buf, offset, offset + len))
          offset += Entry.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineRead () {
    Read.encodingLength = encodingLength
    Read.encode = encode
    Read.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.data)) throw new Error("data is required")
      var len = encodings.bytes.encodingLength(obj.data)
      length += 1 + len
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.data)) throw new Error("data is required")
      buf[offset++] = 10
      encodings.bytes.encode(obj.data, buf, offset)
      offset += encodings.bytes.encode.bytes
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        data: null
      }
      var found0 = false
      while (true) {
        if (end <= offset) {
          if (!found0) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.data = encodings.bytes.decode(buf, offset)
          offset += encodings.bytes.decode.bytes
          found0 = true
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineEndResponse () {
    EndResponse.encodingLength = encodingLength
    EndResponse.encode = encode
    EndResponse.decode = decode

    function encodingLength (obj) {
      var length = 0
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
      }
      while (true) {
        if (end <= offset) {
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineSuccess () {
    Success.encodingLength = encodingLength
    Success.encode = encode
    Success.decode = decode

    function encodingLength (obj) {
      var length = 0
      if ((+defined(obj.handshake) + +defined(obj.ls) + +defined(obj.read) + +defined(obj.endResponse)) > 1) throw new Error("only one of the properties defined in oneof msg can be set")
      if (defined(obj.handshake)) {
        var len = Handshake.encodingLength(obj.handshake)
        length += varint.encodingLength(len)
        length += 1 + len
      }
      if (defined(obj.ls)) {
        var len = Ls.encodingLength(obj.ls)
        length += varint.encodingLength(len)
        length += 1 + len
      }
      if (defined(obj.read)) {
        var len = Read.encodingLength(obj.read)
        length += varint.encodingLength(len)
        length += 1 + len
      }
      if (defined(obj.endResponse)) {
        var len = EndResponse.encodingLength(obj.endResponse)
        length += varint.encodingLength(len)
        length += 1 + len
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if ((+defined(obj.handshake) + +defined(obj.ls) + +defined(obj.read) + +defined(obj.endResponse)) > 1) throw new Error("only one of the properties defined in oneof msg can be set")
      if (defined(obj.handshake)) {
        buf[offset++] = 10
        varint.encode(Handshake.encodingLength(obj.handshake), buf, offset)
        offset += varint.encode.bytes
        Handshake.encode(obj.handshake, buf, offset)
        offset += Handshake.encode.bytes
      }
      if (defined(obj.ls)) {
        buf[offset++] = 18
        varint.encode(Ls.encodingLength(obj.ls), buf, offset)
        offset += varint.encode.bytes
        Ls.encode(obj.ls, buf, offset)
        offset += Ls.encode.bytes
      }
      if (defined(obj.read)) {
        buf[offset++] = 26
        varint.encode(Read.encodingLength(obj.read), buf, offset)
        offset += varint.encode.bytes
        Read.encode(obj.read, buf, offset)
        offset += Read.encode.bytes
      }
      if (defined(obj.endResponse)) {
        buf[offset++] = 34
        varint.encode(EndResponse.encodingLength(obj.endResponse), buf, offset)
        offset += varint.encode.bytes
        EndResponse.encode(obj.endResponse, buf, offset)
        offset += EndResponse.encode.bytes
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        handshake: null,
        ls: null,
        read: null,
        endResponse: null
      }
      while (true) {
        if (end <= offset) {
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          delete obj.ls
          delete obj.read
          delete obj.endResponse
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.handshake = Handshake.decode(buf, offset, offset + len)
          offset += Handshake.decode.bytes
          break
          case 2:
          delete obj.handshake
          delete obj.read
          delete obj.endResponse
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.ls = Ls.decode(buf, offset, offset + len)
          offset += Ls.decode.bytes
          break
          case 3:
          delete obj.handshake
          delete obj.ls
          delete obj.endResponse
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.read = Read.decode(buf, offset, offset + len)
          offset += Read.decode.bytes
          break
          case 4:
          delete obj.handshake
          delete obj.ls
          delete obj.read
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.endResponse = EndResponse.decode(buf, offset, offset + len)
          offset += EndResponse.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  Response.encodingLength = encodingLength
  Response.encode = encode
  Response.decode = decode

  function encodingLength (obj) {
    var length = 0
    if ((+defined(obj.err) + +defined(obj.success)) > 1) throw new Error("only one of the properties defined in oneof response can be set")
    if (defined(obj.err)) {
      var len = encodings.int32.encodingLength(obj.err)
      length += 1 + len
    }
    if (defined(obj.success)) {
      var len = Success.encodingLength(obj.success)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if ((+defined(obj.err) + +defined(obj.success)) > 1) throw new Error("only one of the properties defined in oneof response can be set")
    if (defined(obj.err)) {
      buf[offset++] = 8
      encodings.int32.encode(obj.err, buf, offset)
      offset += encodings.int32.encode.bytes
    }
    if (defined(obj.success)) {
      buf[offset++] = 18
      varint.encode(Success.encodingLength(obj.success), buf, offset)
      offset += varint.encode.bytes
      Success.encode(obj.success, buf, offset)
      offset += Success.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      err: 0,
      success: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        delete obj.success
        obj.err = encodings.int32.decode(buf, offset)
        offset += encodings.int32.decode.bytes
        break
        case 2:
        delete obj.err
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.success = Success.decode(buf, offset, offset + len)
        offset += Success.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
