// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var ClientMessage = exports.ClientMessage = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var ServerMessage = exports.ServerMessage = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineClientMessage()
defineServerMessage()

function defineClientMessage () {
  var Readdir = ClientMessage.Readdir = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Cat = ClientMessage.Cat = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Find = ClientMessage.Find = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Download = ClientMessage.Download = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Swarm = ClientMessage.Swarm = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Wishlist = ClientMessage.Wishlist = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  defineReaddir()
  defineCat()
  defineFind()
  defineDownload()
  defineSwarm()
  defineWishlist()

  function defineReaddir () {
    Readdir.encodingLength = encodingLength
    Readdir.encode = encode
    Readdir.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.path)) throw new Error("path is required")
      var len = encodings.string.encodingLength(obj.path)
      length += 1 + len
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.path)) throw new Error("path is required")
      buf[offset++] = 10
      encodings.string.encode(obj.path, buf, offset)
      offset += encodings.string.encode.bytes
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        path: ""
      }
      var found0 = false
      while (true) {
        if (end <= offset) {
          if (!found0) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.path = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          found0 = true
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineCat () {
    Cat.encodingLength = encodingLength
    Cat.encode = encode
    Cat.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.path)) throw new Error("path is required")
      var len = encodings.string.encodingLength(obj.path)
      length += 1 + len
      if (defined(obj.start)) {
        var len = encodings.varint.encodingLength(obj.start)
        length += 1 + len
      }
      if (defined(obj.end)) {
        var len = encodings.varint.encodingLength(obj.end)
        length += 1 + len
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.path)) throw new Error("path is required")
      buf[offset++] = 10
      encodings.string.encode(obj.path, buf, offset)
      offset += encodings.string.encode.bytes
      if (defined(obj.start)) {
        buf[offset++] = 16
        encodings.varint.encode(obj.start, buf, offset)
        offset += encodings.varint.encode.bytes
      }
      if (defined(obj.end)) {
        buf[offset++] = 24
        encodings.varint.encode(obj.end, buf, offset)
        offset += encodings.varint.encode.bytes
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        path: "",
        start: 0,
        end: 0
      }
      var found0 = false
      while (true) {
        if (end <= offset) {
          if (!found0) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.path = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          found0 = true
          break
          case 2:
          obj.start = encodings.varint.decode(buf, offset)
          offset += encodings.varint.decode.bytes
          break
          case 3:
          obj.end = encodings.varint.decode(buf, offset)
          offset += encodings.varint.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineFind () {
    Find.encodingLength = encodingLength
    Find.encode = encode
    Find.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (defined(obj.basepath)) {
        var len = encodings.string.encodingLength(obj.basepath)
        length += 1 + len
      }
      if (defined(obj.searchterm)) {
        var len = encodings.string.encodingLength(obj.searchterm)
        length += 1 + len
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (defined(obj.basepath)) {
        buf[offset++] = 10
        encodings.string.encode(obj.basepath, buf, offset)
        offset += encodings.string.encode.bytes
      }
      if (defined(obj.searchterm)) {
        buf[offset++] = 18
        encodings.string.encode(obj.searchterm, buf, offset)
        offset += encodings.string.encode.bytes
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        basepath: "",
        searchterm: ""
      }
      while (true) {
        if (end <= offset) {
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.basepath = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          break
          case 2:
          obj.searchterm = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineDownload () {
    Download.encodingLength = encodingLength
    Download.encode = encode
    Download.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.path)) throw new Error("path is required")
      var len = encodings.string.encodingLength(obj.path)
      length += 1 + len
      if (defined(obj.destination)) {
        var len = encodings.string.encodingLength(obj.destination)
        length += 1 + len
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.path)) throw new Error("path is required")
      buf[offset++] = 10
      encodings.string.encode(obj.path, buf, offset)
      offset += encodings.string.encode.bytes
      if (defined(obj.destination)) {
        buf[offset++] = 26
        encodings.string.encode(obj.destination, buf, offset)
        offset += encodings.string.encode.bytes
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        path: "",
        destination: ""
      }
      var found0 = false
      while (true) {
        if (end <= offset) {
          if (!found0) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.path = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          found0 = true
          break
          case 3:
          obj.destination = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineSwarm () {
    Swarm.encodingLength = encodingLength
    Swarm.encode = encode
    Swarm.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.name)) throw new Error("name is required")
      var len = encodings.string.encodingLength(obj.name)
      length += 1 + len
      if (!defined(obj.join)) throw new Error("join is required")
      var len = encodings.bool.encodingLength(obj.join)
      length += 1 + len
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.name)) throw new Error("name is required")
      buf[offset++] = 10
      encodings.string.encode(obj.name, buf, offset)
      offset += encodings.string.encode.bytes
      if (!defined(obj.join)) throw new Error("join is required")
      buf[offset++] = 16
      encodings.bool.encode(obj.join, buf, offset)
      offset += encodings.bool.encode.bytes
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        name: "",
        join: false
      }
      var found0 = false
      var found1 = false
      while (true) {
        if (end <= offset) {
          if (!found0 || !found1) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.name = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          found0 = true
          break
          case 2:
          obj.join = encodings.bool.decode(buf, offset)
          offset += encodings.bool.decode.bytes
          found1 = true
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineWishlist () {
    Wishlist.encodingLength = encodingLength
    Wishlist.encode = encode
    Wishlist.decode = decode

    function encodingLength (obj) {
      var length = 0
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
      }
      while (true) {
        if (end <= offset) {
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  ClientMessage.encodingLength = encodingLength
  ClientMessage.encode = encode
  ClientMessage.decode = decode

  function encodingLength (obj) {
    var length = 0
    if ((+defined(obj.readdir) + +defined(obj.cat) + +defined(obj.find) + +defined(obj.download) + +defined(obj.wishlist) + +defined(obj.swarm)) > 1) throw new Error("only one of the properties defined in oneof msg can be set")
    if (!defined(obj.id)) throw new Error("id is required")
    var len = encodings.varint.encodingLength(obj.id)
    length += 1 + len
    if (defined(obj.readdir)) {
      var len = Readdir.encodingLength(obj.readdir)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    if (defined(obj.cat)) {
      var len = Cat.encodingLength(obj.cat)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    if (defined(obj.find)) {
      var len = Find.encodingLength(obj.find)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    if (defined(obj.download)) {
      var len = Download.encodingLength(obj.download)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    if (defined(obj.wishlist)) {
      var len = Wishlist.encodingLength(obj.wishlist)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    if (defined(obj.swarm)) {
      var len = Swarm.encodingLength(obj.swarm)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if ((+defined(obj.readdir) + +defined(obj.cat) + +defined(obj.find) + +defined(obj.download) + +defined(obj.wishlist) + +defined(obj.swarm)) > 1) throw new Error("only one of the properties defined in oneof msg can be set")
    if (!defined(obj.id)) throw new Error("id is required")
    buf[offset++] = 8
    encodings.varint.encode(obj.id, buf, offset)
    offset += encodings.varint.encode.bytes
    if (defined(obj.readdir)) {
      buf[offset++] = 18
      varint.encode(Readdir.encodingLength(obj.readdir), buf, offset)
      offset += varint.encode.bytes
      Readdir.encode(obj.readdir, buf, offset)
      offset += Readdir.encode.bytes
    }
    if (defined(obj.cat)) {
      buf[offset++] = 26
      varint.encode(Cat.encodingLength(obj.cat), buf, offset)
      offset += varint.encode.bytes
      Cat.encode(obj.cat, buf, offset)
      offset += Cat.encode.bytes
    }
    if (defined(obj.find)) {
      buf[offset++] = 34
      varint.encode(Find.encodingLength(obj.find), buf, offset)
      offset += varint.encode.bytes
      Find.encode(obj.find, buf, offset)
      offset += Find.encode.bytes
    }
    if (defined(obj.download)) {
      buf[offset++] = 42
      varint.encode(Download.encodingLength(obj.download), buf, offset)
      offset += varint.encode.bytes
      Download.encode(obj.download, buf, offset)
      offset += Download.encode.bytes
    }
    if (defined(obj.wishlist)) {
      buf[offset++] = 50
      varint.encode(Wishlist.encodingLength(obj.wishlist), buf, offset)
      offset += varint.encode.bytes
      Wishlist.encode(obj.wishlist, buf, offset)
      offset += Wishlist.encode.bytes
    }
    if (defined(obj.swarm)) {
      buf[offset++] = 58
      varint.encode(Swarm.encodingLength(obj.swarm), buf, offset)
      offset += varint.encode.bytes
      Swarm.encode(obj.swarm, buf, offset)
      offset += Swarm.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      id: 0,
      readdir: null,
      cat: null,
      find: null,
      download: null,
      wishlist: null,
      swarm: null
    }
    var found0 = false
    while (true) {
      if (end <= offset) {
        if (!found0) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.id = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        found0 = true
        break
        case 2:
        delete obj.cat
        delete obj.find
        delete obj.download
        delete obj.wishlist
        delete obj.swarm
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.readdir = Readdir.decode(buf, offset, offset + len)
        offset += Readdir.decode.bytes
        break
        case 3:
        delete obj.readdir
        delete obj.find
        delete obj.download
        delete obj.wishlist
        delete obj.swarm
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.cat = Cat.decode(buf, offset, offset + len)
        offset += Cat.decode.bytes
        break
        case 4:
        delete obj.readdir
        delete obj.cat
        delete obj.download
        delete obj.wishlist
        delete obj.swarm
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.find = Find.decode(buf, offset, offset + len)
        offset += Find.decode.bytes
        break
        case 5:
        delete obj.readdir
        delete obj.cat
        delete obj.find
        delete obj.wishlist
        delete obj.swarm
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.download = Download.decode(buf, offset, offset + len)
        offset += Download.decode.bytes
        break
        case 6:
        delete obj.readdir
        delete obj.cat
        delete obj.find
        delete obj.download
        delete obj.swarm
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.wishlist = Wishlist.decode(buf, offset, offset + len)
        offset += Wishlist.decode.bytes
        break
        case 7:
        delete obj.readdir
        delete obj.cat
        delete obj.find
        delete obj.download
        delete obj.wishlist
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.swarm = Swarm.decode(buf, offset, offset + len)
        offset += Swarm.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineServerMessage () {
  var Readdir = ServerMessage.Readdir = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Find = ServerMessage.Find = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Download = ServerMessage.Download = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Upload = ServerMessage.Upload = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var EndResponse = ServerMessage.EndResponse = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Cat = ServerMessage.Cat = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Wishlist = ServerMessage.Wishlist = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var PeerConnected = ServerMessage.PeerConnected = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var PeerDisconnected = ServerMessage.PeerDisconnected = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Swarm = ServerMessage.Swarm = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  var Success = ServerMessage.Success = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  defineReaddir()
  defineFind()
  defineDownload()
  defineUpload()
  defineEndResponse()
  defineCat()
  defineWishlist()
  definePeerConnected()
  definePeerDisconnected()
  defineSwarm()
  defineSuccess()

  function defineReaddir () {
    var Stat = Readdir.Stat = {
      buffer: true,
      encodingLength: null,
      encode: null,
      decode: null
    }

    defineStat()

    function defineStat () {
      Stat.encodingLength = encodingLength
      Stat.encode = encode
      Stat.decode = decode

      function encodingLength (obj) {
        var length = 0
        if (!defined(obj.name)) throw new Error("name is required")
        var len = encodings.string.encodingLength(obj.name)
        length += 1 + len
        if (!defined(obj.size)) throw new Error("size is required")
        var len = encodings.varint.encodingLength(obj.size)
        length += 1 + len
        if (defined(obj.mode)) {
          var len = encodings.varint.encodingLength(obj.mode)
          length += 1 + len
        }
        return length
      }

      function encode (obj, buf, offset) {
        if (!offset) offset = 0
        if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
        var oldOffset = offset
        if (!defined(obj.name)) throw new Error("name is required")
        buf[offset++] = 10
        encodings.string.encode(obj.name, buf, offset)
        offset += encodings.string.encode.bytes
        if (!defined(obj.size)) throw new Error("size is required")
        buf[offset++] = 16
        encodings.varint.encode(obj.size, buf, offset)
        offset += encodings.varint.encode.bytes
        if (defined(obj.mode)) {
          buf[offset++] = 24
          encodings.varint.encode(obj.mode, buf, offset)
          offset += encodings.varint.encode.bytes
        }
        encode.bytes = offset - oldOffset
        return buf
      }

      function decode (buf, offset, end) {
        if (!offset) offset = 0
        if (!end) end = buf.length
        if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
        var oldOffset = offset
        var obj = {
          name: "",
          size: 0,
          mode: 0
        }
        var found0 = false
        var found1 = false
        while (true) {
          if (end <= offset) {
            if (!found0 || !found1) throw new Error("Decoded message is not valid")
            decode.bytes = offset - oldOffset
            return obj
          }
          var prefix = varint.decode(buf, offset)
          offset += varint.decode.bytes
          var tag = prefix >> 3
          switch (tag) {
            case 1:
            obj.name = encodings.string.decode(buf, offset)
            offset += encodings.string.decode.bytes
            found0 = true
            break
            case 2:
            obj.size = encodings.varint.decode(buf, offset)
            offset += encodings.varint.decode.bytes
            found1 = true
            break
            case 3:
            obj.mode = encodings.varint.decode(buf, offset)
            offset += encodings.varint.decode.bytes
            break
            default:
            offset = skip(prefix & 7, buf, offset)
          }
        }
      }
    }

    Readdir.encodingLength = encodingLength
    Readdir.encode = encode
    Readdir.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (defined(obj.files)) {
        for (var i = 0; i < obj.files.length; i++) {
          if (!defined(obj.files[i])) continue
          var len = Stat.encodingLength(obj.files[i])
          length += varint.encodingLength(len)
          length += 1 + len
        }
      }
      if (defined(obj.path)) {
        var len = encodings.string.encodingLength(obj.path)
        length += 1 + len
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (defined(obj.files)) {
        for (var i = 0; i < obj.files.length; i++) {
          if (!defined(obj.files[i])) continue
          buf[offset++] = 10
          varint.encode(Stat.encodingLength(obj.files[i]), buf, offset)
          offset += varint.encode.bytes
          Stat.encode(obj.files[i], buf, offset)
          offset += Stat.encode.bytes
        }
      }
      if (defined(obj.path)) {
        buf[offset++] = 18
        encodings.string.encode(obj.path, buf, offset)
        offset += encodings.string.encode.bytes
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        files: [],
        path: ""
      }
      while (true) {
        if (end <= offset) {
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.files.push(Stat.decode(buf, offset, offset + len))
          offset += Stat.decode.bytes
          break
          case 2:
          obj.path = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineFind () {
    Find.encodingLength = encodingLength
    Find.encode = encode
    Find.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (defined(obj.results)) {
        for (var i = 0; i < obj.results.length; i++) {
          if (!defined(obj.results[i])) continue
          var len = encodings.string.encodingLength(obj.results[i])
          length += 1 + len
        }
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (defined(obj.results)) {
        for (var i = 0; i < obj.results.length; i++) {
          if (!defined(obj.results[i])) continue
          buf[offset++] = 10
          encodings.string.encode(obj.results[i], buf, offset)
          offset += encodings.string.encode.bytes
        }
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        results: []
      }
      while (true) {
        if (end <= offset) {
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.results.push(encodings.string.decode(buf, offset))
          offset += encodings.string.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineDownload () {
    Download.encodingLength = encodingLength
    Download.encode = encode
    Download.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.bytesRead)) throw new Error("bytesRead is required")
      var len = encodings.varint.encodingLength(obj.bytesRead)
      length += 1 + len
      if (!defined(obj.totalBytesRead)) throw new Error("totalBytesRead is required")
      var len = encodings.varint.encodingLength(obj.totalBytesRead)
      length += 1 + len
      if (defined(obj.filePath)) {
        var len = encodings.string.encodingLength(obj.filePath)
        length += 1 + len
      }
      if (defined(obj.fullFilePath)) {
        var len = encodings.string.encodingLength(obj.fullFilePath)
        length += 1 + len
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.bytesRead)) throw new Error("bytesRead is required")
      buf[offset++] = 8
      encodings.varint.encode(obj.bytesRead, buf, offset)
      offset += encodings.varint.encode.bytes
      if (!defined(obj.totalBytesRead)) throw new Error("totalBytesRead is required")
      buf[offset++] = 16
      encodings.varint.encode(obj.totalBytesRead, buf, offset)
      offset += encodings.varint.encode.bytes
      if (defined(obj.filePath)) {
        buf[offset++] = 26
        encodings.string.encode(obj.filePath, buf, offset)
        offset += encodings.string.encode.bytes
      }
      if (defined(obj.fullFilePath)) {
        buf[offset++] = 34
        encodings.string.encode(obj.fullFilePath, buf, offset)
        offset += encodings.string.encode.bytes
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        bytesRead: 0,
        totalBytesRead: 0,
        filePath: "",
        fullFilePath: ""
      }
      var found0 = false
      var found1 = false
      while (true) {
        if (end <= offset) {
          if (!found0 || !found1) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.bytesRead = encodings.varint.decode(buf, offset)
          offset += encodings.varint.decode.bytes
          found0 = true
          break
          case 2:
          obj.totalBytesRead = encodings.varint.decode(buf, offset)
          offset += encodings.varint.decode.bytes
          found1 = true
          break
          case 3:
          obj.filePath = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          break
          case 4:
          obj.fullFilePath = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineUpload () {
    Upload.encodingLength = encodingLength
    Upload.encode = encode
    Upload.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.bytesRead)) throw new Error("bytesRead is required")
      var len = encodings.varint.encodingLength(obj.bytesRead)
      length += 1 + len
      if (!defined(obj.totalBytesRead)) throw new Error("totalBytesRead is required")
      var len = encodings.varint.encodingLength(obj.totalBytesRead)
      length += 1 + len
      if (defined(obj.filePath)) {
        var len = encodings.string.encodingLength(obj.filePath)
        length += 1 + len
      }
      if (defined(obj.fullFilePath)) {
        var len = encodings.string.encodingLength(obj.fullFilePath)
        length += 1 + len
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.bytesRead)) throw new Error("bytesRead is required")
      buf[offset++] = 8
      encodings.varint.encode(obj.bytesRead, buf, offset)
      offset += encodings.varint.encode.bytes
      if (!defined(obj.totalBytesRead)) throw new Error("totalBytesRead is required")
      buf[offset++] = 16
      encodings.varint.encode(obj.totalBytesRead, buf, offset)
      offset += encodings.varint.encode.bytes
      if (defined(obj.filePath)) {
        buf[offset++] = 26
        encodings.string.encode(obj.filePath, buf, offset)
        offset += encodings.string.encode.bytes
      }
      if (defined(obj.fullFilePath)) {
        buf[offset++] = 34
        encodings.string.encode(obj.fullFilePath, buf, offset)
        offset += encodings.string.encode.bytes
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        bytesRead: 0,
        totalBytesRead: 0,
        filePath: "",
        fullFilePath: ""
      }
      var found0 = false
      var found1 = false
      while (true) {
        if (end <= offset) {
          if (!found0 || !found1) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.bytesRead = encodings.varint.decode(buf, offset)
          offset += encodings.varint.decode.bytes
          found0 = true
          break
          case 2:
          obj.totalBytesRead = encodings.varint.decode(buf, offset)
          offset += encodings.varint.decode.bytes
          found1 = true
          break
          case 3:
          obj.filePath = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          break
          case 4:
          obj.fullFilePath = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineEndResponse () {
    EndResponse.encodingLength = encodingLength
    EndResponse.encode = encode
    EndResponse.decode = decode

    function encodingLength (obj) {
      var length = 0
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
      }
      while (true) {
        if (end <= offset) {
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineCat () {
    Cat.encodingLength = encodingLength
    Cat.encode = encode
    Cat.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.data)) throw new Error("data is required")
      var len = encodings.bytes.encodingLength(obj.data)
      length += 1 + len
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.data)) throw new Error("data is required")
      buf[offset++] = 10
      encodings.bytes.encode(obj.data, buf, offset)
      offset += encodings.bytes.encode.bytes
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        data: null
      }
      var found0 = false
      while (true) {
        if (end <= offset) {
          if (!found0) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.data = encodings.bytes.decode(buf, offset)
          offset += encodings.bytes.decode.bytes
          found0 = true
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineWishlist () {
    Wishlist.encodingLength = encodingLength
    Wishlist.encode = encode
    Wishlist.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (defined(obj.item)) {
        for (var i = 0; i < obj.item.length; i++) {
          if (!defined(obj.item[i])) continue
          var len = encodings.string.encodingLength(obj.item[i])
          length += 1 + len
        }
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (defined(obj.item)) {
        for (var i = 0; i < obj.item.length; i++) {
          if (!defined(obj.item[i])) continue
          buf[offset++] = 10
          encodings.string.encode(obj.item[i], buf, offset)
          offset += encodings.string.encode.bytes
        }
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        item: []
      }
      while (true) {
        if (end <= offset) {
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.item.push(encodings.string.decode(buf, offset))
          offset += encodings.string.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function definePeerConnected () {
    PeerConnected.encodingLength = encodingLength
    PeerConnected.encode = encode
    PeerConnected.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.name)) throw new Error("name is required")
      var len = encodings.string.encodingLength(obj.name)
      length += 1 + len
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.name)) throw new Error("name is required")
      buf[offset++] = 10
      encodings.string.encode(obj.name, buf, offset)
      offset += encodings.string.encode.bytes
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        name: ""
      }
      var found0 = false
      while (true) {
        if (end <= offset) {
          if (!found0) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.name = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          found0 = true
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function definePeerDisconnected () {
    PeerDisconnected.encodingLength = encodingLength
    PeerDisconnected.encode = encode
    PeerDisconnected.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.name)) throw new Error("name is required")
      var len = encodings.string.encodingLength(obj.name)
      length += 1 + len
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.name)) throw new Error("name is required")
      buf[offset++] = 10
      encodings.string.encode(obj.name, buf, offset)
      offset += encodings.string.encode.bytes
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        name: ""
      }
      var found0 = false
      while (true) {
        if (end <= offset) {
          if (!found0) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.name = encodings.string.decode(buf, offset)
          offset += encodings.string.decode.bytes
          found0 = true
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineSwarm () {
    Swarm.encodingLength = encodingLength
    Swarm.encode = encode
    Swarm.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (defined(obj.connected)) {
        for (var i = 0; i < obj.connected.length; i++) {
          if (!defined(obj.connected[i])) continue
          var len = encodings.string.encodingLength(obj.connected[i])
          length += 1 + len
        }
      }
      if (defined(obj.disconnected)) {
        for (var i = 0; i < obj.disconnected.length; i++) {
          if (!defined(obj.disconnected[i])) continue
          var len = encodings.string.encodingLength(obj.disconnected[i])
          length += 1 + len
        }
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (defined(obj.connected)) {
        for (var i = 0; i < obj.connected.length; i++) {
          if (!defined(obj.connected[i])) continue
          buf[offset++] = 10
          encodings.string.encode(obj.connected[i], buf, offset)
          offset += encodings.string.encode.bytes
        }
      }
      if (defined(obj.disconnected)) {
        for (var i = 0; i < obj.disconnected.length; i++) {
          if (!defined(obj.disconnected[i])) continue
          buf[offset++] = 18
          encodings.string.encode(obj.disconnected[i], buf, offset)
          offset += encodings.string.encode.bytes
        }
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        connected: [],
        disconnected: []
      }
      while (true) {
        if (end <= offset) {
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.connected.push(encodings.string.decode(buf, offset))
          offset += encodings.string.decode.bytes
          break
          case 2:
          obj.disconnected.push(encodings.string.decode(buf, offset))
          offset += encodings.string.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  function defineSuccess () {
    Success.encodingLength = encodingLength
    Success.encode = encode
    Success.decode = decode

    function encodingLength (obj) {
      var length = 0
      if ((+defined(obj.endResponse) + +defined(obj.readdir) + +defined(obj.cat) + +defined(obj.find) + +defined(obj.download) + +defined(obj.upload) + +defined(obj.wishlist) + +defined(obj.swarm)) > 1) throw new Error("only one of the properties defined in oneof msg can be set")
      if (defined(obj.endResponse)) {
        var len = EndResponse.encodingLength(obj.endResponse)
        length += varint.encodingLength(len)
        length += 1 + len
      }
      if (defined(obj.readdir)) {
        var len = Readdir.encodingLength(obj.readdir)
        length += varint.encodingLength(len)
        length += 1 + len
      }
      if (defined(obj.cat)) {
        var len = Cat.encodingLength(obj.cat)
        length += varint.encodingLength(len)
        length += 1 + len
      }
      if (defined(obj.find)) {
        var len = Find.encodingLength(obj.find)
        length += varint.encodingLength(len)
        length += 1 + len
      }
      if (defined(obj.download)) {
        var len = Download.encodingLength(obj.download)
        length += varint.encodingLength(len)
        length += 1 + len
      }
      if (defined(obj.upload)) {
        var len = Upload.encodingLength(obj.upload)
        length += varint.encodingLength(len)
        length += 1 + len
      }
      if (defined(obj.wishlist)) {
        var len = Wishlist.encodingLength(obj.wishlist)
        length += varint.encodingLength(len)
        length += 1 + len
      }
      if (defined(obj.swarm)) {
        var len = Swarm.encodingLength(obj.swarm)
        length += varint.encodingLength(len)
        length += 1 + len
      }
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if ((+defined(obj.endResponse) + +defined(obj.readdir) + +defined(obj.cat) + +defined(obj.find) + +defined(obj.download) + +defined(obj.upload) + +defined(obj.wishlist) + +defined(obj.swarm)) > 1) throw new Error("only one of the properties defined in oneof msg can be set")
      if (defined(obj.endResponse)) {
        buf[offset++] = 10
        varint.encode(EndResponse.encodingLength(obj.endResponse), buf, offset)
        offset += varint.encode.bytes
        EndResponse.encode(obj.endResponse, buf, offset)
        offset += EndResponse.encode.bytes
      }
      if (defined(obj.readdir)) {
        buf[offset++] = 18
        varint.encode(Readdir.encodingLength(obj.readdir), buf, offset)
        offset += varint.encode.bytes
        Readdir.encode(obj.readdir, buf, offset)
        offset += Readdir.encode.bytes
      }
      if (defined(obj.cat)) {
        buf[offset++] = 26
        varint.encode(Cat.encodingLength(obj.cat), buf, offset)
        offset += varint.encode.bytes
        Cat.encode(obj.cat, buf, offset)
        offset += Cat.encode.bytes
      }
      if (defined(obj.find)) {
        buf[offset++] = 34
        varint.encode(Find.encodingLength(obj.find), buf, offset)
        offset += varint.encode.bytes
        Find.encode(obj.find, buf, offset)
        offset += Find.encode.bytes
      }
      if (defined(obj.download)) {
        buf[offset++] = 42
        varint.encode(Download.encodingLength(obj.download), buf, offset)
        offset += varint.encode.bytes
        Download.encode(obj.download, buf, offset)
        offset += Download.encode.bytes
      }
      if (defined(obj.upload)) {
        buf[offset++] = 50
        varint.encode(Upload.encodingLength(obj.upload), buf, offset)
        offset += varint.encode.bytes
        Upload.encode(obj.upload, buf, offset)
        offset += Upload.encode.bytes
      }
      if (defined(obj.wishlist)) {
        buf[offset++] = 58
        varint.encode(Wishlist.encodingLength(obj.wishlist), buf, offset)
        offset += varint.encode.bytes
        Wishlist.encode(obj.wishlist, buf, offset)
        offset += Wishlist.encode.bytes
      }
      if (defined(obj.swarm)) {
        buf[offset++] = 66
        varint.encode(Swarm.encodingLength(obj.swarm), buf, offset)
        offset += varint.encode.bytes
        Swarm.encode(obj.swarm, buf, offset)
        offset += Swarm.encode.bytes
      }
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        endResponse: null,
        readdir: null,
        cat: null,
        find: null,
        download: null,
        upload: null,
        wishlist: null,
        swarm: null
      }
      while (true) {
        if (end <= offset) {
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          delete obj.readdir
          delete obj.cat
          delete obj.find
          delete obj.download
          delete obj.upload
          delete obj.wishlist
          delete obj.swarm
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.endResponse = EndResponse.decode(buf, offset, offset + len)
          offset += EndResponse.decode.bytes
          break
          case 2:
          delete obj.endResponse
          delete obj.cat
          delete obj.find
          delete obj.download
          delete obj.upload
          delete obj.wishlist
          delete obj.swarm
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.readdir = Readdir.decode(buf, offset, offset + len)
          offset += Readdir.decode.bytes
          break
          case 3:
          delete obj.endResponse
          delete obj.readdir
          delete obj.find
          delete obj.download
          delete obj.upload
          delete obj.wishlist
          delete obj.swarm
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.cat = Cat.decode(buf, offset, offset + len)
          offset += Cat.decode.bytes
          break
          case 4:
          delete obj.endResponse
          delete obj.readdir
          delete obj.cat
          delete obj.download
          delete obj.upload
          delete obj.wishlist
          delete obj.swarm
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.find = Find.decode(buf, offset, offset + len)
          offset += Find.decode.bytes
          break
          case 5:
          delete obj.endResponse
          delete obj.readdir
          delete obj.cat
          delete obj.find
          delete obj.upload
          delete obj.wishlist
          delete obj.swarm
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.download = Download.decode(buf, offset, offset + len)
          offset += Download.decode.bytes
          break
          case 6:
          delete obj.endResponse
          delete obj.readdir
          delete obj.cat
          delete obj.find
          delete obj.download
          delete obj.wishlist
          delete obj.swarm
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.upload = Upload.decode(buf, offset, offset + len)
          offset += Upload.decode.bytes
          break
          case 7:
          delete obj.endResponse
          delete obj.readdir
          delete obj.cat
          delete obj.find
          delete obj.download
          delete obj.upload
          delete obj.swarm
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.wishlist = Wishlist.decode(buf, offset, offset + len)
          offset += Wishlist.decode.bytes
          break
          case 8:
          delete obj.endResponse
          delete obj.readdir
          delete obj.cat
          delete obj.find
          delete obj.download
          delete obj.upload
          delete obj.wishlist
          var len = varint.decode(buf, offset)
          offset += varint.decode.bytes
          obj.swarm = Swarm.decode(buf, offset, offset + len)
          offset += Swarm.decode.bytes
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  ServerMessage.encodingLength = encodingLength
  ServerMessage.encode = encode
  ServerMessage.decode = decode

  function encodingLength (obj) {
    var length = 0
    if ((+defined(obj.err) + +defined(obj.success)) > 1) throw new Error("only one of the properties defined in oneof response can be set")
    if (!defined(obj.id)) throw new Error("id is required")
    var len = encodings.varint.encodingLength(obj.id)
    length += 1 + len
    if (defined(obj.err)) {
      var len = encodings.int32.encodingLength(obj.err)
      length += 1 + len
    }
    if (defined(obj.success)) {
      var len = Success.encodingLength(obj.success)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if ((+defined(obj.err) + +defined(obj.success)) > 1) throw new Error("only one of the properties defined in oneof response can be set")
    if (!defined(obj.id)) throw new Error("id is required")
    buf[offset++] = 8
    encodings.varint.encode(obj.id, buf, offset)
    offset += encodings.varint.encode.bytes
    if (defined(obj.err)) {
      buf[offset++] = 16
      encodings.int32.encode(obj.err, buf, offset)
      offset += encodings.int32.encode.bytes
    }
    if (defined(obj.success)) {
      buf[offset++] = 26
      varint.encode(Success.encodingLength(obj.success), buf, offset)
      offset += varint.encode.bytes
      Success.encode(obj.success, buf, offset)
      offset += Success.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      id: 0,
      err: 0,
      success: null
    }
    var found0 = false
    while (true) {
      if (end <= offset) {
        if (!found0) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.id = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        found0 = true
        break
        case 2:
        delete obj.success
        obj.err = encodings.int32.decode(buf, offset)
        offset += encodings.int32.decode.bytes
        break
        case 3:
        delete obj.err
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.success = Success.decode(buf, offset, offset + len)
        offset += Success.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
